name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: apphost.ocf.berkeley.edu
      SSH_USERNAME: eecsdiscord
      SSH_PORT: 22
    steps:
    - name: Stop eecsbot
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        port: ${{ env.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: systemctl --user stop eecsbot

    - name: Generate .env
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_OWNER_ID: ${{ secrets.BOT_OWNER_ID }}
        EMAIL: ${{ secrets.EMAIL }}
        PASS: ${{ secrets.PASS }}
        PEPPER: ${{ secrets.PEPPER }}
      run: |
        cat << EOF >> .env
        BOT_TOKEN=$BOT_TOKEN
        BOT_OWNER_ID=$BOT_OWNER_ID
        EMAIL=$EMAIL
        PASS=$PASS
        PEPPER=$PEPPER
        EOF

    - name: SCP .env
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        port: ${{ env.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".env"
        target: "./eecsbot/"

    - name: Build eecsbot
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        port: ${{ env.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ./eecsbot
          git fetch origin master
          git reset --hard origin/master
          nvm use || nvm install
          nvm install-latest-npm
          nvm alias default node
          rm -rf node_modules
          npm ci --python=python3.7
          npm run build

    - name: Start eecsbot
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        port: ${{ env.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: systemctl --user start eecsbot
